### ISSUE TITLE
TypeError: uri_template is not a string

### ISSUE THREAD

**Issue by nishankmahore** [explosion/spacy-services#4]
Getting this error while running displacy/app.py

> Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from displacy.server import APP, get_model
  File "/apps/nishank/api/spacy-services/displacy/displacy/server.py", line 136, in <module>
    APP.add_route('/dep', DepResource())
  File "/apps/conda/lib/python2.7/site-packages/falcon/api.py", line 194, in add_route
    uri_fields, path_template = helpers.compile_uri_template(uri_template)
  File "/apps/conda/lib/python2.7/site-packages/falcon/api_helpers.py", line 145, in compile_uri_template
    raise TypeError('uri_template is not a string')
TypeError: uri_template is not a string

**Comment by honnibal** [comment]
I think this should be fixed now. I'm still a little worried about Python 2/3 compatibility, though.
